1.5.16 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/migration-assistant/ma-script-utils b/d-i/source/migration-assistant/ma-script-utils
--- a/d-i/source/migration-assistant/ma-script-utils
+++ b/d-i/source/migration-assistant/ma-script-utils
@@ -27,6 +27,11 @@ set_os_type () {
         return 0
 	;;
 
+        Windows[0-9] )
+        ostype="windowsxp"
+        return 0
+        ;;
+
 	"Windows9xMe" )
 	ostype="windows9x"
         return 0
@@ -46,6 +51,8 @@ set_os_type () {
 mountpoint="/mnt/migrationassistant"
 
 unmount_os() {
+    # If we didn't mount the device ourselves, don't unmount it.
+    [ "$mountpoint" = "/mnt/migrationassistant" ] || return 0
     device="$1"
 
     if [ -f /etc/mtab ]; then
@@ -94,51 +101,61 @@ mount_os () {
     ostype="$1"
     device="$2"
 
-    mkdir -p $mountpoint
-    unmount_os $device
 
     if [ "$1" = "linux" ]; then
-	mount $device $mountpoint
-	if [ -f "$mountpoint/etc/fstab" ]; then
+        mkdir -p $mountpoint
+        unmount_os $device
+        mount $device $mountpoint || error "Failed to mount $device"
+        if [ -f "$mountpoint/etc/fstab" ]; then
             while read uuid mp rest; do
-	    	if [ "$mp" != "/home" ]; then
-		    continue
-		fi
+                if [ "$mp" != "/home" ]; then
+                    continue
+                fi
 
-		if [ "${uuid%=*}" = "UUID" ]; then
+                if [ "${uuid%=*}" = "UUID" ]; then
                     devname="/dev/disk/by-uuid/${uuid#*=}"
-		    uuid=$(readlink -e "$devname") || \
-                        error "$devname does not exist."
-		elif [ "${uuid%=*}" = "LABEL" ]; then
-		    devname="/dev/disk/by-label/${uuid#*=}"
                     uuid=$(readlink -e "$devname") || \
                         error "$devname does not exist."
-                elif [ ! -e "$uuid" ]; then
-                    # This happens when the IDE driver in the old OS doesn't
-                    # match the driver in the installer.  The old /home might be
-                    # mounted on /dev/hda3 which could now be /dev/sda3 or
-                    # something entirely different.  Since there's no way to
-                    # determine what the device is without the old kernel
-                    # loaded, we fail gracefully so that we can continue to the
-                    # next OS.
-                    log "$uuid does not exist, continuing."
-                    break
-                fi
-                failed=
-		mount $uuid "$mountpoint/home" || failed="1"
-                if [ "$failed" ]; then
-		    unmount_os "$uuid"
-		    mount $uuid "$mountpoint/home" || \
+                elif [ "${uuid%=*}" = "LABEL" ]; then
+                    devname="/dev/disk/by-label/${uuid#*=}"
+                    uuid=$(readlink -e "$devname") || \
+                        error "$devname does not exist."
+                    elif [ ! -e "$uuid" ]; then
+                        # This happens when the IDE driver in the old OS
+                        # doesn't match the driver in the installer.  The old
+                        # /home might be mounted on /dev/hda3 which could now
+                        # be /dev/sda3 or something entirely different.  Since
+                        # there's no way to determine what the device is
+                        # without the old kernel loaded, we fail gracefully so
+                        # that we can continue to the next OS.
+                        log "$uuid does not exist, continuing."
+                        break
+                    fi
+                    failed=
+                    mount $uuid "$mountpoint/home" || failed="1"
+                        if [ "$failed" ]; then
+                    unmount_os "$uuid"
+                    mount $uuid "$mountpoint/home" || \
                         error "failed to mount $uuid"
-		fi
-		break
+                fi
+                break
             done < "$mountpoint/etc/fstab"
         fi
     elif [ "$1" = "windowsxp" ]; then
-	mount -t ntfs $device $mountpoint -o umask=0022,nls=utf8 || \
-	( log "Mounting $device to $mountpoint with NTFS failed."
-	mount -t vfat $device $mountpoint -o umask=0022,utf8 || \
-	log "Mounting $device to $mountpoint with VFAT failed." )
+        # Since we don't have to worry about separate partitions making up the
+        # whole system in Windows (yet), we can allow already mounted
+        # partitions.  This may fix some corner cases.  At any rate, it's
+        # required for Wubi to function properly.
+        [ -f /etc/mtab ] && mnt=$(grep "$device" /etc/mtab|cut -d " " -f 2) \
+        [ -z "$mnt" ] && mnt=$(grep "$device" /proc/partitions|cut -d " " -f 2) \
+        [ -n "$mnt" ] && mountpoint=$mnt && return 0
+
+        mkdir -p $mountpoint
+        unmount_os $device
+        mount -t ntfs $device $mountpoint -o umask=0022,nls=utf8 || \
+        ( log "Mounting $device to $mountpoint with NTFS failed."
+        mount -t vfat $device $mountpoint -o umask=0022,utf8 || \
+        log "Mounting $device to $mountpoint with VFAT failed." )
     fi
 
 }
