1.3.2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/partman-auto/auto.d/initial_auto b/d-i/source/partman-auto/auto.d/initial_auto
--- a/d-i/source/partman-auto/auto.d/initial_auto
+++ b/d-i/source/partman-auto/auto.d/initial_auto
@@ -33,23 +33,78 @@ fi
 [ -d /var/lib/partman ] || mkdir /var/lib/partman
 touch /var/lib/partman/initial_auto
 
-# See if a disk to autopartition (either classic or LVM) has been set
+# See if any autopartition method has been set
+method=""
+if db_get partman-auto/method && [ -n "$RET" ]; then
+	method="$RET"
+fi
+
+# See if any autopartition disks have been set
+disks=""
 if db_get partman-auto/disk && [ -n "$RET" ]; then
-	disk="$RET"
-	id=$(dev_to_partman "$disk") || true
-	if [ -n "$id" ]; then
-		autopartition "$id"
-		exit 0
-	fi
-elif search-path autopartition-lvm && \
-     db_get partman-auto-lvm/disk && [ -n "$RET" ]; then
-	disk="$RET"
-	id=$(dev_to_partman "$disk") || true
-	if [ -n "$id" ]; then
-		autopartition-lvm "$id"
-		exit 0
-	fi
+	disks="$RET"
+fi
+
+# If both are set, let's try to do a completely automatic partitioning
+if [ -n "$method" ] && [ -n "$disks" ]; then
+	# The code for the methods could be merged, but in the future non-regular
+	# methods may support multiple disks
+	case "$method" in
+		regular)
+			for disk in $disks; do
+				id=$(dev_to_partman "$disk") || true
+				if [ -n "$id" ]; then
+					autopartition "$id"
+					exit 0
+				fi
+			done
+			exit 1
+			;;
+		lvm)
+			search-path autopartition-lvm || exit 1
+			for disk in $disks; do
+				id=$(dev_to_partman "$disk") || true
+				if [ -n "$id" ]; then
+					autopartition-lvm "$id"
+					exit 0
+				fi
+			done
+			exit 1
+			;;
+		crypto)
+			search-path autopartition-crypto || exit 1
+			for disk in $disks; do
+				id=$(dev_to_partman "$disk") || true
+				if [ -n "$id" ]; then
+					autopartition-crypto "$id"
+					exit 0
+				fi
+			done
+			exit 1
+			;;
+		raid)
+			# Partition all the disks given ready for
+			# partman-auto-raid
+			for disk in $disks; do
+				id=$(dev_to_partman "$disk") || true
+				if [ -n "$id" ]; then
+					autopartition "$id"
+				fi
+			done
+			exit 0
+			;;
+		*)
+			# Unsupported method
+			exit 1
+			;;
+	esac
 fi
 
 echo "partman-auto/init_automatically_partition" > /lib/partman/automatically_partition/question
-partman_newlayout
+code=99 # signals a retry
+while [ $code = 99 ]; do
+	ask_user /lib/partman/automatically_partition 
+	code=$?
+done
+echo "partman-auto/automatically_partition" > /lib/partman/automatically_partition/question
+exit $code
diff --git a/d-i/source/partman-auto/choose_partition/auto/do_option b/d-i/source/partman-auto/choose_partition/auto/do_option
--- a/d-i/source/partman-auto/choose_partition/auto/do_option
+++ b/d-i/source/partman-auto/choose_partition/auto/do_option
@@ -1,3 +1,10 @@
 #!/bin/sh
 
-partman_newlayout
+. /lib/partman/definitions.sh
+
+code=99 # signals a retry
+while [ $code = 99 ]; do
+	ask_user /lib/partman/automatically_partition
+	code=$?
+done
+exit $code
