2.7.30 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
--- a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
+++ b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
@@ -115,6 +115,11 @@ omap_flash_kernel_installer() {
 
 	install_mkimage
 
+	# xloader is still a separate package for beagle
+	if ! apt-install x-loader-omap3-beagle; then
+		error "apt-install x-loader-omap3-beagle failed"
+	fi
+
 	uboot_pkg="u-boot-linaro-omap3-beagle"
 	omap_install_uboot
 }
