2.3.0 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
--- a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
+++ b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
@@ -17,15 +17,40 @@ error() {
 }
 
 findfs () {
-	mount | grep "on /target${1%/} " | cut -d' ' -f1
+	mount | grep "on /target${1%/} " | tail -n1 | cut -d' ' -f1
 }
 
 # Are we writing to flash or constructing an image on disk?
 write_to_flash() {
 	case "$machine" in
-		"Buffalo Linkstation Pro/Live" | "Buffalo/Revogear Kurobox Pro" | "GLAN Tank" | "HP Media Vault mv2120" | "Marvell DB-MV88F6781-BP Development Board")
+		"Buffalo Linkstation Pro/Live")
 			return 1
 		;;
+		"Buffalo/Revogear Kurobox Pro")
+			return 1
+		;;
+		"GLAN Tank")
+			return 1
+		;;
+		"HP Media Vault mv2120")
+			return 1
+		;;
+		"Marvell OpenRD Base Board")
+			return 1
+		;;
+		"Marvell OpenRD Client Board")
+			return 1
+		;;
+		"Marvell SheevaPlug Reference Board")
+			return 1
+		;;
+		"Marvell eSATA SheevaPlug Reference Board")
+			return 1
+		;;
+        "Marvell DB-MV88F6781-BP Development Board")
+            return 1
+        ;;
+		# Assume that we write to flash for all other devices
 		*)
 			return 0
 		;;
@@ -49,15 +74,10 @@ if ! apt-install flash-kernel; then
 	error "apt-install flash-kernel failed"
 fi
 
-# Set up flash-kernel to run on kernel upgrades.
-if ! grep -q flash-kernel /target/etc/kernel-img.conf; then
-	echo "postinst_hook = flash-kernel" >> \
-		/target/etc/kernel-img.conf
-fi
-
 # Temporarily move flash-kernel out of the way so update-initramfs
-# won't call flash-kernel; otherwise we'd call it twice.
+# won't call flash-kernel; otherwise we might call it twice.
 mv /target/usr/sbin/flash-kernel /target/tmp/flash-kernel.$$
+trap "mv /target/tmp/flash-kernel.$$ /target/usr/sbin/flash-kernel" EXIT HUP INT QUIT TERM
 
 db_progress STEP 1
 
@@ -196,14 +216,23 @@ case "$machine" in
 		in-target fw_setenv bootargs "${cmdline}"
 		in-target fw_setenv bootdelay 3
     ;;
-	"Thecus N2100" | "Thecus N4100")
-		in-target update-initramfs -u || true
-	;;
-	"QNAP TS-109/TS-209" | "QNAP TS-409")
+	"Marvell OpenRD Base Board" | "Marvell OpenRD Client Board" | "Marvell SheevaPlug Reference Board" | "Marvell eSATA SheevaPlug Reference Board")
 		in-target update-initramfs -u || true
 		if ! apt-install uboot-mkimage; then
 			error "apt-install uboot-mkimage failed"
 		fi
+	;;
+	"Thecus N2100" | "Thecus N4100")
+		in-target update-initramfs -u || true
+	;;
+	"QNAP TS-109/TS-209" | "QNAP TS-119/TS-219" | "QNAP TS-409" | "QNAP TS-41x")
+		in-target update-initramfs -u || true
+		if ! apt-install uboot-mkimage; then
+			error "apt-install uboot-mkimage failed"
+		fi
+	;;
+	"Lanner EM7210")
+		in-target update-initramfs -u || true
 	;;
 esac
 
@@ -214,6 +243,7 @@ else
 	db_progress INFO flash-kernel-installer/generating_image
 fi
 
+trap - EXIT HUP INT QUIT TERM
 mv /target/tmp/flash-kernel.$$ /target/usr/sbin/flash-kernel
 
 # We need the udev /dev which has the MTD devices
diff --git a/d-i/source/flash-kernel/flash-kernel b/d-i/source/flash-kernel/flash-kernel
--- a/d-i/source/flash-kernel/flash-kernel
+++ b/d-i/source/flash-kernel/flash-kernel
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Copyright (C) 2006  Joey Hess  <joeyh@debian.org>
-# Copyright (C) 2006, 2007, 2008  Martin Michlmayr <tbm@cyrius.com>
+# Copyright (C) 2006, 2007, 2008, 2009  Martin Michlmayr <tbm@cyrius.com>
 
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -102,9 +102,9 @@ sercomm_header() {
 
 nslu2_swap() {
 	if [ "$little_endian" ]; then
-		devio "<<"$1 "xp $,4"
+		devio "<<$1" "xp $,4"
 	else
-		cat $1
+		cat "$1"
 	fi
 }
 
@@ -123,7 +123,12 @@ if [ -r "$config" ]; then
     . "$config"
 fi
 
-machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
+if [ "x$1" = "x--machine" ]; then
+	machine=$2
+	shift 2
+else
+	machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
+fi
 
 if [ "x$1" = "x--supported" ]; then
 	case "$machine" in
@@ -136,8 +141,15 @@ if [ "x$1" = "x--supported" ]; then
 		"Marvell DB-MV88F6781-BP Development Board") exit 0 ;;
 		"Linksys NSLU2")			exit 0 ;;
 		"OMAP3 Beagle Board")			exit 0 ;;
+		"Marvell OpenRD Base Board")		exit 0 ;;
+		"Marvell OpenRD Client Board")		exit 0 ;;
+		"Marvell SheevaPlug Reference Board")	exit 0 ;;
+		"Marvell eSATA SheevaPlug Reference Board")	exit 0 ;;
 		"QNAP TS-109/TS-209" | "QNAP TS-409")	exit 0 ;;
+		"QNAP TS-119/TS-219")			exit 0 ;;
+		"QNAP TS-41x")				exit 0 ;;
 		"Thecus N2100")				exit 0 ;;
+		"Lanner EM7210")			exit 0 ;;
 		*)					exit 1 ;;
 	esac
 fi
@@ -165,8 +177,8 @@ fi
 if [ ! -e $kfile ] || [ ! -e $ifile ]; then
 	error "Can't find $kfile and $ifile"
 fi
-kfilesize=$(wc -c $kfile | awk '{print $1}')
-ifilesize=$(wc -c $ifile | awk '{print $1}')
+kfilesize=$(wc -c "$kfile" | awk '{print $1}')
+ifilesize=$(wc -c "$ifile" | awk '{print $1}')
 
 # Extract the subarchitecture from the kernel name
 if [ -L "$kfile" ]; then
@@ -177,39 +189,39 @@ subarch=$(echo "$kfile" | sed -e 's/.*-//')
 case "$machine" in
 	"Buffalo Linkstation Pro/Live" | "Buffalo/Revogear Kurobox Pro")
 		check_subarch "orion5x"
-		tmp=$(tempfile)
+		tmp="$(tempfile)"
 		printf "Generating kernel u-boot image... " >&2
 		case "$machine" in
 			"Buffalo Linkstation Pro/Live")
 				# Set machine id 1585 (0x0631)
-				devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe3811031,4'
+				devio > "$tmp" 'wl 0xe3a01c06,4' 'wl 0xe3811031,4'
 			;;
 			"Buffalo/Revogear Kurobox Pro")
 				# Set machine id 1509 (0x05e5)
-				devio > $tmp 'wl 0xe3a01c05,4' 'wl 0xe38110e5,4'
+				devio > "$tmp" 'wl 0xe3a01c05,4' 'wl 0xe38110e5,4'
 			;;
 		esac
-		cat $kfile >> $tmp
+		cat "$kfile" >> "$tmp"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
-			-e 0x00008000 -n "$desc" -d $tmp $tmp.uboot >&2 1>/dev/null
+			-e 0x00008000 -n "$desc" -d "$tmp" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
 		if [ -e /boot/uImage.buffalo ]; then
 			echo "Creating backup of /boot/uImage.buffalo." >&2
 			mv /boot/uImage.buffalo /boot/uImage.buffalo.bak
 		fi
 		echo "Creating new /boot/uImage.buffalo." >&2
-		mv $tmp.uboot /boot/uImage.buffalo
-		rm -f $tmp
+		mv "$tmp.uboot" /boot/uImage.buffalo
+		rm -f "$tmp"
 		printf "Generating initrd u-boot image... " >&2
 		mkimage -A arm -O linux -T ramdisk -C gzip -a 0x0 \
-			-e 0x0 -n "$idesc" -d $ifile $tmp.uboot >&2 1>/dev/null
+			-e 0x0 -n "$idesc" -d "$ifile" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
 		if [ -e /boot/initrd.buffalo ]; then
 			echo "Creating backup of /boot/initrd.buffalo." >&2
 			mv /boot/initrd.buffalo /boot/initrd.buffalo.bak
 		fi
 		echo "Creating new /boot/initrd.buffalo." >&2
-		mv $tmp.uboot /boot/initrd.buffalo
+		mv "$tmp.uboot" /boot/initrd.buffalo
 	;;
 	"D-Link DNS-323")
 		check_subarch "orion5x"
@@ -229,24 +241,25 @@ case "$machine" in
 		kmtdsize=$(mtdsize "Linux Kernel")
 		check_size "Linux Kernel" $(($kfilesize + 8 + 64)) $kmtdsize
 		printf "Generating kernel u-boot image... " >&2
-		tmp=$(tempfile)
+		tmp="$(tempfile)"
 		# Set machine id 1542 (0x0606)
-		devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe3811006,4'
-		cat $kfile >> $tmp
+		devio > "$tmp" 'wl 0xe3a01c06,4' 'wl 0xe3811006,4'
+		cat "$kfile" >> "$tmp"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
-			-e 0x00008000 -n "$desc" -d $tmp $tmp.uboot >&2 1>/dev/null
+			-e 0x00008000 -n "$desc" -d "$tmp" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
 		printf "Flashing kernel... " >&2
-		cat $tmp.uboot > $kmtd || error "failed."
+		cat "$tmp.uboot" > "$kmtd" || error "failed."
 		echo "done." >&2
-		rm -f $tmp.uboot $tmp
+		rm -f "$tmp.uboot" "$tmp"
 		printf "Generating initramfs u-boot image... " >&2
 		mkimage -A arm -O linux -T ramdisk -C gzip -a 0x00800000 \
-			-e 0x00800000 -n "$idesc" -d $ifile $tmp.uboot >&2 1>/dev/null
-		printf "Flashing initramfs... " >&2
-		cat $tmp.uboot > $imtd || error "failed."
+			-e 0x00800000 -n "$idesc" -d "$ifile" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
-		rm -f $tmp.uboot
+		printf "Flashing initramfs... " >&2
+		cat "$tmp.uboot" > "$imtd" || error "failed."
+		echo "done." >&2
+		rm -f "$tmp.uboot"
 	;;
 	"Freescale MX51 Babbage Board")
 		check_subarch "imx51"
@@ -326,30 +339,30 @@ case "$machine" in
 	;;
 	"GLAN Tank")
 		rm -f /boot/initrd /boot/zImage
-		ln -s $(basename $ifile) /boot/initrd
+		ln -s "$(basename "$ifile")" /boot/initrd
 		(
 			# Set machine id 1100 (0x044c)
 			devio 'wl 0xe3a01c04,4' 'wl 0xe381104c,4'
-			cat $kfile
+			cat "$kfile"
 		) > /boot/zImage
 	;;
 	"HP Media Vault mv2120")
 		check_subarch "orion5x"
-		tmp=$(tempfile)
+		tmp="$(tempfile)"
 		printf "Generating kernel u-boot image... " >&2
 		# Set machine id 1693 (0x069d)
-		devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe381109d,4'
-		cat $kfile >> $tmp
+		devio > "$tmp" 'wl 0xe3a01c06,4' 'wl 0xe381109d,4'
+		cat "$kfile" >> "$tmp"
 		mkimage -A arm -O linux -T multi -C none -n "$desc" -a 0x01000000 \
-			-e 0x01000000 -d $tmp:$ifile $tmp.uboot >&2 1>/dev/null
+			-e 0x01000000 -d "$tmp:$ifile" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
 		if [ -e /boot/uImage ]; then
 			echo "Creating backup of /boot/uImage." >&2
 			mv /boot/uImage /boot/uImage.bak
 		fi
 		echo "Creating new /boot/uImage." >&2
-		mv $tmp.uboot /boot/uImage
-		rm -f $tmp
+		mv "$tmp.uboot" /boot/uImage
+		rm -f "$tmp"
 	;;
 	"Linksys NSLU2")
 		check_subarch "ixp4xx"
@@ -412,26 +425,51 @@ case "$machine" in
 		# headers.
 		boundary=1441792 # 0x00160000
 		ksize1=$(expr $boundary - $offset - 16)
-		tmp=$(tempfile)
+		tmp="$(tempfile)"
 		printf "Flashing kernel: " >&2
 		(
 			sercomm_header $(expr $kfilesize + 16)
-			dd if=$kfile of=$tmp bs=$ksize1 count=1 2>/dev/null
-			nslu2_swap $tmp
+			dd if="$kfile" of="$tmp" bs=$ksize1 count=1 2>/dev/null
+			nslu2_swap "$tmp"
 			sercomm_header 131072
-			dd if=$kfile of=$tmp ibs=$ksize1 skip=1 2>/dev/null
-			nslu2_swap $tmp
-			rm -f $tmp
+			dd if="$kfile" of="$tmp" ibs=$ksize1 skip=1 2>/dev/null
+			nslu2_swap "$tmp"
+			rm -f "$tmp"
 		) > "$kmtd" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs: " >&2
-		dd if=$ifile of=$tmp ibs=$(($imtdsize - 16)) conv=sync 2>/dev/null
+		dd if="$ifile" of="$tmp" ibs=$(($imtdsize - 16)) conv=sync 2>/dev/null
 		(
 			sercomm_header $ifilesize
-			nslu2_swap $tmp
-			rm -f $tmp
-		) > $imtd || error "failed."
+			nslu2_swap "$tmp"
+			rm -f "$tmp"
+		) > "$imtd" || error "failed."
 		echo "done." >&2
+	;;
+	"Marvell OpenRD Base Board" | "Marvell OpenRD Client Board" | "Marvell SheevaPlug Reference Board" | "Marvell eSATA SheevaPlug Reference Board")
+		check_subarch "kirkwood"
+		tmp="$(tempfile)"
+		printf "Generating kernel u-boot image... " >&2
+		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
+			-e 0x00008000 -n "$desc" -d "$kfile" "$tmp.uboot" >&2 1>/dev/null
+		echo "done." >&2
+		if [ -e /boot/uImage ]; then
+			echo "Creating backup of /boot/uImage." >&2
+			mv /boot/uImage /boot/uImage.bak
+		fi
+		echo "Creating new /boot/uImage." >&2
+		mv "$tmp.uboot" /boot/uImage
+		printf "Generating initrd u-boot image... " >&2
+		mkimage -A arm -O linux -T ramdisk -C gzip -a 0x0 \
+			-e 0x0 -n "$idesc" -d "$ifile" "$tmp.uboot" >&2 1>/dev/null
+		echo "done." >&2
+		if [ -e /boot/uInitrd ]; then
+			echo "Creating backup of /boot/uInitrd." >&2
+			mv /boot/uInitrd /boot/uInitrd.bak
+		fi
+		echo "Creating new /boot/uInitrd." >&2
+		mv "$tmp.uboot" /boot/uInitrd
+		rm -f "$tmp"
 	;;
 	"Marvell DB-MV88F6781-BP Development Board")
 		check_subarch "dove"
@@ -570,8 +608,15 @@ EOF
 		echo "done." >&2 
 		rm -f $tmp.uboot $tmp
 	;;
-	"QNAP TS-109/TS-209" | "QNAP TS-409")
-		check_subarch "orion5x"
+	"QNAP TS-109/TS-209" | "QNAP TS-119/TS-219" | "QNAP TS-409" | "QNAP TS-41x")
+		case "$machine" in
+			"QNAP TS-109/TS-209" | "QNAP TS-409")
+				check_subarch "orion5x"
+			;;
+			"QNAP TS-119/TS-219" | "QNAP TS-41x")
+				check_subarch "kirkwood"
+			;;
+		esac
 		check_mtd
 		imtd=$(mtdblock "RootFS1")
 		if [ -z "$imtd" ]; then
@@ -588,31 +633,39 @@ EOF
 		kmtdsize=$(mtdsize "Kernel")
 		check_size "Kernel" $(($kfilesize + 8 + 64)) $kmtdsize
 		printf "Generating kernel u-boot image... " >&2
-		tmp=$(tempfile)
+		tmp="$(tempfile)"
 		case "$machine" in
 			"QNAP TS-109/TS-209")
 				# Set machine id 1565 (0x061d)
-				devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe381101d,4'
+				devio > "$tmp" 'wl 0xe3a01c06,4' 'wl 0xe381101d,4'
+			;;
+			"QNAP TS-119/TS-219")
+				# Set machine id 2139 (0x085b)
+				devio > "$tmp" 'wl 0xe3a01c08,4' 'wl 0xe381105b,4'
 			;;
 			"QNAP TS-409")
 				# Set machine id 1601 (0x0641)
-				devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe3811041,4'
+				devio > "$tmp" 'wl 0xe3a01c06,4' 'wl 0xe3811041,4'
+			;;
+			"QNAP TS-41x")
+				# Set machine id 2502 (0x09c6)
+				devio > "$tmp" 'wl 0xe3a01c09,4' 'wl 0xe38110c6,4'
 			;;
 		esac
-		cat $kfile >> $tmp
+		cat "$kfile" >> "$tmp"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
-			-e 0x00008000 -n "$desc" -d $tmp $tmp.uboot >&2 1>/dev/null
+			-e 0x00008000 -n "$desc" -d "$tmp" "$tmp.uboot" >&2 1>/dev/null
 		echo "done." >&2
 		printf "Flashing kernel... " >&2
-		cat $tmp.uboot > $kmtd || error "failed."
+		cat "$tmp.uboot" > "$kmtd" || error "failed."
 		echo "done." >&2
-		rm -f $tmp.uboot $tmp
+		rm -f "$tmp.uboot" "$tmp"
 		printf "Flashing initramfs... " >&2
 		pad=$(expr $imtdsize - $ifilesize)
 		(
-			cat $ifile
+			cat "$ifile"
 			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > $imtd || error "failed."
+		) > "$imtd" || error "failed."
 		echo "done." >&2
 	;;
 	"Thecus N2100")
@@ -636,15 +689,47 @@ EOF
 		(
 			# Set machine id 1101 (0x044d)
 			devio 'wl 0xe3a01c04,4' 'wl 0xe381104d,4'
-			cat $kfile
-		) > $kmtd || error "failed."
+			cat "$kfile"
+		) > "$kmtd" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs... " >&2
 		pad=$(expr $imtdsize - $ifilesize)
 		(
-			cat $ifile
+			cat "$ifile"
 			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > $imtd || error "failed."
+		) > "$imtd" || error "failed."
+		echo "done." >&2
+	;;
+	"Lanner EM7210")
+		# Really: Intel SS4000-e and compatibles
+		check_subarch "iop32x"
+		check_mtd
+		imtd=$(mtdblock "ramdisk.gz")
+		if [ -z "$imtd" ]; then
+			error "Cannot find mtd partition 'ramdisk.gz'"
+		fi
+		check_dev_mtdblock "$imtd"
+		imtdsize=$(mtdsize "ramdisk.gz")
+		check_size "ramdisk" $ifilesize $imtdsize
+		kmtd=$(mtdblock zImage)
+		if [ -z "$kmtd" ]; then
+			error "Cannot find mtd partition 'zImage'"
+		fi
+		kmtdsize=$(mtdsize "zImage")
+		check_size "zImage" $(($kfilesize + 8)) $kmtdsize
+		printf "Flashing kernel..." >&2
+		(
+			# Set machine ID 1212 (0x04bc)
+			devio 'wl 0xe3a01c04,4' 'wl 0xe38110bc,4'
+			cat "$kfile"
+		) > "$kmtd" || error "failed."
+		echo "done." >&2
+		printf "Flashing initramfs... " >&2
+		pad=$(expr $imtdsize - $ifilesize)
+		(
+			cat "$ifile"
+			dd if=/dev/zero bs=$pad count=1 2>/dev/null
+		) > "$imtd" || error "failed."
 		echo "done." >&2
 	;;
 	*)
