1.12.2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/partman-base/init.d/parted b/d-i/source/partman-base/init.d/parted
--- a/d-i/source/partman-base/init.d/parted
+++ b/d-i/source/partman-base/init.d/parted
@@ -60,62 +60,8 @@ if [ ! -f /var/run/parted_server.pid ]; then
 	fi
 	mkdir $DEVICES || true
 
-	# Exclude devices that have mounted partitions.
-	disks=
-	while :; do
-		disks=
-		parts=
-		db_get partman/filter_mounted
-		if [ "$RET" = false ]; then
-			break
-		fi
-		while read dev rest; do
-			# Taken from split_device() in grub-installer.
-			disk=
-			case $dev in
-				/dev/[vhs]d[a-z]*)
-					disk="$(echo "$dev" | sed 's,\(/dev/[a-z]\+\).*,\1,')"
-				;;
-				/dev/*/c*d*)
-					disk="$(echo "$dev" | sed 's,\(/dev/.*/c[0-9]\+d[0-9]\+\).*,\1,')"
-				;;
-				/dev/mmcblk*)
-					disk="$(echo "$dev" | sed 's,\(/dev/mmcblk[0-9]\+\).*,\1,')"
-				;;
-			esac
-			if [ -z "$disk" ]; then
-				continue
-			fi
-			if [ -n "$disks" ]; then
-				disks="$disks\|$disk"
-				parts="$parts $dev"
-			else
-				disks="$disk"
-				parts="$dev"
-			fi
-		done < /proc/mounts
-		if [ -z "$disks" ]; then
-			break
-		fi
-		db_subst partman/unmount_active DISKS "$(echo "$disks" | sed 's:\\|:, :g')"
-		db_fset partman/unmount_active seen false
-		db_input critical partman/unmount_active || true
-		db_go || exit 10
-		db_get partman/unmount_active || RET=
-		if [ "$RET" = true ]; then
-			umount $parts || true
-		else
-			break
-		fi
-	done
-	if [ "$disks" ]; then
-		disks="^\($disks\)"
-	else
-		disks="^$"
-	fi
 	IFS="$NL"
 	for partdev in $(parted_devices |
-		grep -v "$disks" |
 		sed 's,^/dev/\(ide\|scsi\|[hs]d\|md/\?[0-9]\+\),!/dev/\1,' |
 		sort |
 		sed 's,^!,,' ); do
@@ -182,6 +128,103 @@ if [ ! -f /var/run/parted_server.pid ]; then
 			rm -rf $dev
 		fi
 	done
+
+	# Get a list of active mounts in a more convenient format.
+	mounts=
+	while read dev mp rest; do
+		[ -e "$dev" ] || continue
+		mappeddev="$(mapdevfs "$dev")"
+		if [ "$mappeddev" ]; then
+			dev="$mappeddev"
+		fi
+		mounts="${mounts:+$mounts$NL}$dev $mp"
+	done < /proc/mounts
+	# For each disk, check for any active mounts on it. If the only
+	# thing mounted is the installation medium and it uses more or less
+	# the whole disk, then silently exclude that disk; if the
+	# installation medium is mounted but doesn't use the whole disk,
+	# issue a warning that partitioning may be difficult; if anything
+	# else is mounted, offer to unmount it.
+	disks_unmount=
+	parts_unmount=
+	part_warn=
+	for dev in $DEVICES/*; do
+		[ -d "$dev" ] || continue
+		cd $dev
+		free=0
+		parts=
+		instparts=
+		seen_unmounted=
+		open_dialog PARTITIONS
+		while { read_line num id size type fs path name; [ "$id" ]; }; do
+			if [ "$fs" = free ]; then
+				free="$(($free + $size))"
+				continue
+			fi
+			mappedpath="$(mapdevfs "$path")"
+			if [ "$mappedpath" ]; then
+				path="$mappedpath"
+			fi
+			mp=
+			IFS="$NL"
+			for line in $mounts; do
+				restore_ifs
+				if [ "$path" = "${line%% *}" ]; then
+					mp="${line#* }"
+					break
+				fi
+				IFS="$NL"
+			done
+			restore_ifs
+			if [ "$mp" = /cdrom ]; then
+				instparts="${instparts:+$instparts }$path"
+			elif [ "$mp" ]; then
+				parts="${parts:+$parts }$path"
+			else
+				seen_unmounted=1
+			fi
+		done
+		close_dialog
+		if [ "$instparts" ]; then
+			if [ -z "$seen_unmounted" ] && \
+			   longint_le "$free" 16777216; then
+				# The installation medium uses more or less
+				# the whole disk.
+				open_dialog CLOSE
+				close_dialog
+				cd /
+				rm -rf "$dev"
+			else
+				# There's an installation medium here, but
+				# it doesn't use the whole disk.
+				part_warn="$instparts"
+				>installation_medium
+			fi
+		elif [ "$parts" ]; then
+			# Something other than an installation medium is
+			# mounted.
+			disks_unmount="${disks_unmount:+$disks_unmount }$(cat device)"
+			parts_unmount="${parts_unmount:+$parts_unmount }$parts"
+		fi
+	done
+	if [ "$disks_unmount" ]; then
+		db_subst partman/unmount_active DISKS "$(echo "$disks_unmount" | sed 's/ /, /g')"
+		db_fset partman/unmount_active seen false
+		db_input critical partman/unmount_active || true
+		db_go || exit 10
+		db_get partman/unmount_active || RET=
+		if [ "$RET" = true ]; then
+			umount $parts_unmount || true
+		fi
+	fi
+	if [ "$part_warn" ]; then
+		db_subst partman/installation_medium_mounted PARTITION "$part_warn"
+		db_fset partman/installation_medium_mounted seen false
+		db_capb align
+		db_input high partman/installation_medium_mounted || true
+		db_go || true
+		db_capb backup align
+	fi
 
 	rm -rf /var/lib/partman/old_devices
 fi
