1.7.7 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/apt-setup/apt-setup-verify b/d-i/source/apt-setup/apt-setup-verify
--- a/d-i/source/apt-setup/apt-setup-verify
+++ b/d-i/source/apt-setup/apt-setup-verify
@@ -37,6 +37,11 @@ valid () {
 
 	[ "${line%%:*}" != "deb cdrom" ] || return 0
 
+	# Ubuntu change: network sources are always valid; apt will cope
+	# gracefully later, even though the network may not be available
+	# now.
+	return 0
+
 	tmp=$($chroot $ROOT tempfile)
 	echo "$line" > $ROOT$tmp
 	
@@ -49,6 +54,16 @@ valid () {
 		false
 	fi
 }
+
+# Ubuntu change: need to run apt-get update for everything in one go here,
+# since we've disabled the run in the valid function above. Doing everything
+# in one go also allows apt-get to cache resolver failures and connection
+# timeouts and so be significantly faster when the network is unavailable.
+tmp=$($chroot $ROOT tempfile)
+cat "$file" > $ROOT$tmp
+$logoutput $chroot $ROOT apt-get -o APT::Get::List-Cleanup=false \
+	-o Dir::Etc::sourcelist=$tmp $ASV_TIMEOUT update || true
+rm -f $ROOT$tmp
 
 items=0
 gooditems=0
