1.9.1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/apt-setup/apt-setup-verify b/d-i/source/apt-setup/apt-setup-verify
--- a/d-i/source/apt-setup/apt-setup-verify
+++ b/d-i/source/apt-setup/apt-setup-verify
@@ -8,13 +8,36 @@ NL="
 "
 
 NOTEST=""
-if [ "$1" = "--invalid" ]; then
-	NOTEST=1
+PROGRESS=""
+PROGRESS_FROM=""
+PROGRESS_TO=""
+file=""
+while [ "$1" ]; do
+	case "$1" in
+	    --invalid)
+		NOTEST=1 ;;
+	    --from)
+		shift
+		PROGRESS_FROM=$1 ;;
+	    --to)
+		shift
+		PROGRESS_TO=$1 ;;
+	    *)
+		if [ -z "$file" ]; then
+			file="$1"
+		else
+			saveto="$1"
+		fi ;;
+	esac
 	shift
-fi
+done
 
-file="$1"
-saveto="$2"
+if [ "$PROGRESS_FROM" ] && [ "$PROGRESS_TO" ] && \
+   [ $PROGRESS_FROM -lt $PROGRESS_TO ]; then
+	PROGRESS=1
+else
+	DAP_OPTS="--no-progress"
+fi
 
 logoutput=""
 if [ "$CATCHLOG" ]; then
@@ -22,8 +45,10 @@ if [ "$CATCHLOG" ]; then
 fi
 
 chroot=
+intarget=
 if [ "$ROOT" ]; then
 	chroot=chroot
+	intarget=in-target
 fi
 
 saveline () {
@@ -32,8 +57,14 @@ saveline () {
 	fi
 }
 
+# Option to cancel an action does not currently work:
+# - application does not seem to always react to a cancel signal
+# - debconf-apt-progress does not exit with code 30 when cancelled
+# - even if it did, the exit code would be mangled by in-target
+# See also thread http://lists.debian.org/debian-boot/2008/01/msg00094.html
 valid () {
-	line="$1"
+	local line="$1"
+	local dap_opts="$2"
 
 	[ "${line%%:*}" != "deb cdrom" ] || return 0
 
@@ -44,10 +75,13 @@ valid () {
 
 	tmp=$($chroot $ROOT tempfile)
 	echo "$line" > $ROOT$tmp
-	
-	if $logoutput $chroot $ROOT apt-get -o APT::Get::List-Cleanup=false \
-		-o Dir::Etc::sourcelist=$tmp $ASV_TIMEOUT update
-	then
+	code=0
+	$logoutput $intarget debconf-apt-progress --logstderr $dap_opts -- \
+		apt-get -o APT::Get::List-Cleanup=false \
+			-o Dir::Etc::sourcelist=$tmp $ASV_TIMEOUT update || code=$?
+	if [ $code -eq 30 ]; then
+		exit 30 # canceled
+	elif [ $code -eq 0 ]; then
 		rm -f $ROOT$tmp
 	else
 		rm -f $ROOT$tmp
@@ -65,6 +99,11 @@ $logoutput $chroot $ROOT apt-get -o APT::Get::List-Cleanup=false \
 	-o Dir::Etc::sourcelist=$tmp $ASV_TIMEOUT update || true
 rm -f $ROOT$tmp
 
+if [ "$PROGRESS" ]; then
+	tot_items=$(grep -Ev "^(#.*|)[[:space:]]*$" $file | wc -l)
+	p_from=$PROGRESS_FROM
+fi
+
 items=0
 gooditems=0
 
@@ -75,15 +114,23 @@ IFS="$NL"
 for line in $(sed 's/^/:/' $file); do
 	IFS="$OLDIFS"
 	line="${line#:}"
-	if expr "$line" : '.*[^ ].*' >/dev/null && [ "$(expr "$line" : "#")" != 1 ]; then
-		items=$(expr "$items" + 1)
+	if echo "$line" | grep -Evq "^(#.*|)[[:space:]]*$"; then
+		items=$(expr $items + 1)
 		# Write blank line between generators
 		if [ $items = 1 ] && [ -f "$saveto" ]; then
 			saveline ""
 		fi
 
-		if [ -z "$NOTEST" ] && valid "$line"; then
-			gooditems=$(expr "$gooditems" + 1)
+		if [ "$PROGRESS" ]; then
+			[ $items -eq 1 ] || p_from=$p_to
+			p_to=$(expr $PROGRESS_FROM + \
+				\( $PROGRESS_TO - $PROGRESS_FROM \) \* \
+				$items / $tot_items)
+			DAP_OPTS="--dlwaypoint 100 --from $p_from --to $p_to"
+		fi
+
+		if [ -z "$NOTEST" ] && valid "$line" "$DAP_OPTS"; then
+			gooditems=$(expr $gooditems + 1)
 			saveline "$line"
 		else
 			saveline "# Line commented out by installer because it failed to verify:"
@@ -91,12 +138,12 @@ for line in $(sed 's/^/:/' $file); do
 		fi
 	else
 		# Ignore leading empty lines
-		if [ $items != 0 ] || [ "$line" ]; then
+		if [ $items -ne 0 ] || [ "$line" ]; then
 			saveline "$line"
 		fi
 	fi
 done
 
-if [ "$gooditems" != "$items" ]; then
+if [ $gooditems -ne $items ]; then
 	exit 1
 fi
