1.7.2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/apt-setup/generators/50mirror b/d-i/source/apt-setup/generators/50mirror
--- a/d-i/source/apt-setup/generators/50mirror
+++ b/d-i/source/apt-setup/generators/50mirror
@@ -5,6 +5,9 @@ set -e
 
 file="$1"
 
+NL="
+"
+
 log() {
 	logger -t apt-setup "$@"
 }
@@ -12,28 +15,88 @@ warning() {
 	log "warning: $@"
 }
 
-# Ask if a mirror should be used if the base system can be installed from CD.
+# Ask if a mirror should be used if the base system can be installed from CD
+# Default to false for full CD/DVD images; ask only at medium prio for
+# netinst images and DVDs
 if [ -e /cdrom/.disk/base_installable ] || [ "$OVERRIDE_BASE_INSTALLABLE" ]; then
-	if search-path choose-mirror; then
-		db_input high apt-setup/use_mirror || [ $? -eq 30 ]
-		db_go || exit 10
-	else
+	if ! search-path choose-mirror; then
 		warning "choose-mirror is not available; cannot offer network mirror"
 		exit 1
 	fi
+
+	cd_type=unknown
+	if [ -e /cdrom/.disk/cd_type ]; then
+		cd_type=$(cat /cdrom/.disk/cd_type)
+	fi
+
+	case "$cd_type" in
+	    not_complete)
+		db_metaget apt-mirror/use/netinst description
+		db_subst apt-setup/use_mirror EXPLANATION "$RET"
+		use_mirror=true
+		use_prio=medium ;;
+	    full_cd)
+		db_metaget apt-mirror/use/full_cd1 description
+		explanation="$RET"
+		db_metaget apt-mirror/use/full_cd2 description
+		explanation="$explanation$NL$NL$RET"
+		db_subst apt-setup/use_mirror EXPLANATION "$explanation"
+		use_mirror=true
+		use_prio=high ;;
+	    dvd)
+		db_metaget apt-mirror/use/dvd description
+		db_subst apt-setup/use_mirror EXPLANATION "$RET"
+		use_mirror=false
+		use_prio=high ;;
+	    *)
+		use_mirror=true
+		use_prio=high ;;
+	esac
+
+	# Default to false if no network selected in netcfg
+	if db_get netcfg/dhcp_options && \
+	   [ "$RET" = "Do not configure the network at this time" ]; then
+		use_mirror=false
+		use_prio=medium
+	fi
+
+	# Only set default if not preseeded or already asked
+	# Hack alert: for this to work no default is set in template
+	db_get apt-setup/use_mirror
+	[ "$RET" ] || db_set apt-setup/use_mirror $use_mirror
+
+	db_input $use_prio apt-setup/use_mirror || [ $? -eq 30 ]
+	db_go || exit 10
 
 	db_get apt-setup/use_mirror
 	if [ "$RET" = false ]; then
 		exit 1
 	fi
 
+	# Default suite to codename; choose-mirror will determine actual suite
 	if db_get cdrom/codename && [ "$RET" ]; then
-		db_set mirror/codename $RET
-	fi
-	if db_get cdrom/suite && [ "$RET" ]; then
 		db_set mirror/suite $RET
 	fi
-	choose-mirror -n # no progress bar
+
+	while true; do
+		RET=0
+		choose-mirror -n || RET=$?	# no progress bar
+		if [ $RET -eq 0 ]; then
+			break
+		elif [ $RET -eq 10 ]; then
+			# User backed out of choose-mirror
+			db_input critical apt-setup/no_mirror
+			db_go || exit 10
+
+			db_get apt-setup/no_mirror
+			if [ "$RET" = true ]; then
+				exit 1
+			fi
+		else
+			logger -t apt-setup "choose-mirror failed with error code $RET"
+			exit $RET
+		fi
+	done
 fi
 
 # Abort if no mirror is configured.
@@ -52,29 +115,29 @@ fi
 STATE=1
 while true; do
 	case "$STATE" in
-		1)
-			db_input low apt-setup/non-free || true
+	    1)
+		db_input low apt-setup/non-free || true
 		;;
-		2)
-			# If they chose not to use non-free, ask about
-			# contrib, with a default of no. If they chose to
-			# use non-free, they get contrib too..
-			db_get apt-setup/non-free
+	    2)
+		# If they chose not to use non-free, ask about
+		# contrib, with a default of no. If they chose to
+		# use non-free, they get contrib too..
+		db_get apt-setup/non-free
+		if [ "$RET" = false ]; then
+			db_fget apt-setup/contrib seen
 			if [ "$RET" = false ]; then
-				db_fget apt-setup/contrib seen
-				if [ "$RET" = false ]; then
-					db_set apt-setup/contrib false
-				fi
-				db_input low apt-setup/contrib || true
-			else
-				db_fget apt-setup/contrib seen
-				if [ "$RET" = false ]; then
-					db_set apt-setup/contrib true
-				fi
+				db_set apt-setup/contrib false
 			fi
+			db_input low apt-setup/contrib || true
+		else
+			db_fget apt-setup/contrib seen
+			if [ "$RET" = false ]; then
+				db_set apt-setup/contrib true
+			fi
+		fi
 		;;
-		*)
-			break
+	    *)
+		break
 		;;
 	esac
 
