20.04.7 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/simple-plugins b/scripts/simple-plugins
--- a/scripts/simple-plugins
+++ b/scripts/simple-plugins
@@ -4,15 +4,21 @@ set -e
 . /usr/share/debconf/confmodule
 if [ "$1" = "prepare" ]; then
     FREEONLY="--free-only"
+    NOOEM=""
     db_input high ubiquity/use_nonfree || true
     db_get ubiquity/use_nonfree
     if [ "$RET" = "true" ]; then
 	    FREEONLY=""
     fi
-    env -u DEBIAN_HAS_FRONTEND -u DEBCONF_REDIR \
-        DEBCONF_DB_REPLACE=configdb DEBCONF_DB_OVERRIDE="Pipe{infd:none outfd:none}" \
-        ubuntu-drivers autoinstall $FREEONLY --package-list /run/ubuntu-drivers.autoinstall || \
-            logger -t ubiquity "ubuntu-drivers autoinstall failed with code: $?"
+    db_input high ubiquity/install_oem || true
+    db_get ubiquity/install_oem
+    if [ "$RET" = "false" ]; then
+	    NOOEM="--no-oem"
+    fi
+
+    rm -f /run/ubuntu-drivers.autoinstall
+    ubuntu-drivers install $FREEONLY $NOOEM --package-list /run/ubuntu-drivers.autoinstall || \
+        logger -t ubiquity "ubuntu-drivers install failed with code: $?"
 
     db_input high ubiquity/secureboot_key || true
     db_get ubiquity/secureboot_key
