1.9.2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/d-i/source/localechooser/languagemap b/d-i/source/localechooser/languagemap
--- a/d-i/source/localechooser/languagemap
+++ b/d-i/source/localechooser/languagemap
@@ -1,46 +1,49 @@
 #!/bin/sh
 #
-# This file should be automatically generated.
-#
 # Usage:
-#   LANGNAME="langname"
+#   LANGNAME=<value>
 #   . languagemap
+#
+# The calling script should provide the log() function
 
-for list in /etc/languagelist /usr/share/localechooser/languagelist ./languagelist ; do 
-	if [ -f "$list" ] ; then
+for list in /etc/languagelist /usr/share/localechooser/languagelist ./languagelist; do
+	if [ -f "$list" ]; then
 		languages="$list"
+		break
 	fi
 done
 
-log "LANGNAME=$LANGNAME"
+log "Language = '$LANGUAGE'"
 
-line=$(grep "^${LANGNAME};" $languages || true)
-
+line=$(grep "^$LANGUAGE;" $languages || true)
 log "line=$line"
+
+DEFAULT_COUNTRY=""
+FALLBACKLOCALE=""
+LOCALE=""
+LANGUAGELIST=""
+CONSOLE=""
+
 if [ "$line" ] ; then
 	OLD_IFS="$IFS"
 	IFS=';'
 	set $line
 	IFS="$OLD_IFS"
 
-	#echo "C: $*"
-
-	if [ "$3" ] ; then LANGUAGE="$3" ; fi
-	if [ "$4" ] ; then COUNTRY="$4" ; fi
-	if [ "$5" ] ; then FALLBACKLOCALE="$5" ; LOCALE="$5" ; fi
-	if [ "$6" ] ; then ENCODING="$6"; fi
-	if [ "$7" ] ; then LANGUAGELIST="$7"; fi
-	if [ "$8" ] ; then CONSOLE="$8"; fi
+	if [ "$3" ]; then DEFAULT_COUNTRY="$3" ; fi
+	if [ "$4" ]; then ENCODING="$4"; fi
+	if [ "$5" ]; then FALLBACKLOCALE="$5" ; LOCALE="$5" ; fi
+	if [ "$6" ]; then LANGUAGELIST="$6"; fi
+	if [ "$7" ]; then CONSOLE="$7"; fi
 
 	if [ -z "$LANGUAGELIST" ] ; then
 		LANGUAGELIST="$LANGUAGE"
 	fi
 else
-	echo "error: Unable to locate info on language '$LANGNAME'"
-	log "error: Unable to locate info on language '$LANGNAME'"
-	FALLBACKLOCALE=""
-	LANGUAGE=""
-	LOCALE=C
-	COUNTRY=US
+	log "error: Unable to locate info for language '$LANGUAGE'"
+	LANGUAGE=C
+	DEFAULT_COUNTRY=US
 	ENCODING=""
+	LOCALE=C
+	LANGUAGELIST=en
 fi
